export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/hH4YaZuH89Hlyz0DEkf362Mj8gU.jpg",
    genre_ids: [35],
    id: 65701,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Good Mythical Morning",
    overview:
      'Two "Internetainers" (Rhett & Link) go far out and do the weirdest  things, giving you a daily dose of casual comedy every Monday-Friday.',
    popularity: 4045.184,
    poster_path: "/2Fja87aTeuXxTEI1MH2IuHHSsLq.jpg",
    first_air_date: "2012-01-09",
    name: "Good Mythical Morning",
    vote_average: 7,
    vote_count: 43,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/2yDV0xLyqW88dn5qE7YCRnoYmfy.jpg",
    id: 4613,
    name: "Band of Brothers",
    original_language: "en",
    original_name: "Band of Brothers",
    overview:
      "Drawn from interviews with survivors of Easy Company, as well as their journals and letters, Band of Brothers chronicles the experiences of these men from paratrooper training in Georgia through the end of the war. As an elite rifle company parachuting into Normandy early on D-Day morning, participants in the Battle of the Bulge, and witness to the horrors of war, the men of Easy knew extraordinary bravery and extraordinary fear - and became the stuff of legend. Based on Stephen E. Ambrose's acclaimed book of the same name.",
    poster_path: "/bV7RYiz6YiSfLYynRWNTFdcgEM1.jpg",
    media_type: "tv",
    genre_ids: [18, 10768],
    popularity: 101.509,
    first_air_date: "2001-09-09",
    vote_average: 8.51,
    vote_count: 3278,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/1F2RnXLc0fmRt7iWfBK4mNVsjno.jpg",
    id: 34524,
    name: "Teen Wolf",
    original_language: "en",
    original_name: "Teen Wolf",
    overview:
      "Scott McCall, a high school student living in the town of Beacon Hills has his life drastically changed when he's bitten by a werewolf, becoming one himself. He must henceforth learn to balance his problematic new identity with his day-to-day teenage life. The following characters are instrumental to his struggle: Stiles, his best friend; Allison, his love interest who comes from a family of werewolf hunters; and Derek, a mysterious werewolf with a dark past. Throughout the series, he strives to keep his loved ones safe while maintaining normal relationships with them.",
    poster_path: "/fmlMmxSBgPEunHS5gjokIej048g.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 35],
    popularity: 206.674,
    first_air_date: "2011-06-05",
    vote_average: 8.539,
    vote_count: 3970,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/vcFW09U4834DyFOeRZpsx9x1D3S.jpg",
    id: 57243,
    name: "Doctor Who",
    original_language: "en",
    original_name: "Doctor Who",
    overview:
      "The Doctor is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living—more of a hobby actually, and the Doctor's very, very good at it.",
    poster_path: "/4edFyasCrkH4MKs6H4mHqlrxA6b.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10765],
    popularity: 633.611,
    first_air_date: "2005-03-26",
    vote_average: 7.489,
    vote_count: 2809,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/Aj3hb13leEgC4lmU4YwRC4NaBsk.jpg",
    id: 4556,
    name: "Scrubs",
    original_language: "en",
    original_name: "Scrubs",
    overview:
      'In the unreal world of Sacred Heart Hospital, John "J.D." Dorian learns the ways of medicine, friendship and life.',
    poster_path: "/brJUMAL90m8WSpo9A86S9wZuox6.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 262.87,
    first_air_date: "2001-10-02",
    vote_average: 8,
    vote_count: 1653,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/bp6RoEQMX3lfuZOIPw7Su5c5WCP.jpg",
    id: 387,
    name: "SpongeBob SquarePants",
    original_language: "en",
    original_name: "SpongeBob SquarePants",
    overview:
      "Deep down in the Pacific Ocean in the subterranean city of Bikini Bottom lives a square yellow sponge named SpongeBob SquarePants. SpongeBob lives in a pineapple with his pet snail, Gary, loves his job as a fry cook at the Krusty Krab, and has a knack for getting into all kinds of trouble without really trying. When he's not getting on the nerves of his cranky next door neighbor Squidward, SpongeBob can usually be found smack in the middle of all sorts of strange situations with his best buddy, the simple yet lovable starfish, Patrick, or his thrill-seeking surfer-girl squirrel pal, Sandy Cheeks.",
    poster_path: "/zDuKxQkG8EemvLdBn43ChdM0MJL.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10751, 10765],
    popularity: 76.964,
    first_air_date: "1999-05-01",
    vote_average: 7.621,
    vote_count: 2827,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mmprryb2r0X8u9JkZCnaJIzyYX4.jpg",
    id: 62688,
    name: "Supergirl",
    original_language: "en",
    original_name: "Supergirl",
    overview:
      "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
    poster_path: "/cFO65xb0xiXKqk5BmgHawCXB1i0.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 10759],
    popularity: 286,
    first_air_date: "2015-10-26",
    vote_average: 7.333,
    vote_count: 4061,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/tZmlWeFEMvxrjJhBJJcLNXpSRiG.jpg",
    id: 66573,
    name: "The Good Place",
    original_language: "en",
    original_name: "The Good Place",
    overview:
      "Eleanor Shellstrop, an ordinary woman who, through an extraordinary string of events, enters the afterlife where she comes to realize that she hasn't been a very good person. With the help of her wise afterlife mentor, she's determined to shed her old way of living and discover the awesome (or at least the pretty good) person within.",
    poster_path: "/qIhsuhoIYR5yTnDta0IL4senbeN.jpg",
    media_type: "tv",
    genre_ids: [10765, 35],
    popularity: 75.791,
    first_air_date: "2016-09-19",
    vote_average: 7.979,
    vote_count: 1421,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/soQgquPkLmUu9eKLJJzuA4KZDyi.jpg",
    id: 69050,
    name: "Riverdale",
    original_language: "en",
    original_name: "Riverdale",
    overview:
      "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.",
    poster_path: "/c1ROxK1Afo6YuGi3j6ClXmrNcHi.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 234.249,
    first_air_date: "2017-01-26",
    vote_average: 8.465,
    vote_count: 13280,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rEjhgSvSPlsQOkmYXNzairEvXWB.jpg",
    id: 62823,
    name: "Scream: The TV Series",
    original_language: "en",
    original_name: "Scream: The TV Series",
    overview:
      "What starts as a YouTube video going viral, soon leads to problems for the teenagers of Lakewood and serves as the catalyst for a murder that opens up a window to the town's troubled past. Everyone has secrets. Everyone tells lies. Everyone is fair game.",
    poster_path: "/cTRUcUnAydqboYfis0IhhY1edDt.jpg",
    media_type: "tv",
    genre_ids: [18, 80, 9648],
    popularity: 84.407,
    first_air_date: "2015-06-30",
    vote_average: 6.883,
    vote_count: 1068,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/qsnXwGS7KBbX4JLqHvICngtR8qg.jpg",
    id: 61889,
    name: "Marvel's Daredevil",
    original_language: "en",
    original_name: "Marvel's Daredevil",
    overview:
      "Lawyer-by-day Matt Murdock uses his heightened senses from being blinded as a young boy to fight crime at night on the streets of Hell’s Kitchen as Daredevil.",
    poster_path: "/QWbPaDxiB6LW2LjASknzYBvjMj.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 10759],
    popularity: 123.297,
    first_air_date: "2015-04-10",
    vote_average: 8.2,
    vote_count: 4216,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/hgu56PjfawkpE0anCLfl2b8Uqmr.jpg",
    id: 65329,
    name: "Hyouka",
    original_language: "ja",
    original_name: "氷菓",
    overview:
      'Oreki Houtarou is a minimalistic high school boy. One day, he joins the Classic Literature Club at his elder sister\'s request. There he meets Chitanda Eru, Fukube Satoshi, and Ibara Mayaka. Chitanda is a calm beautiful girl but she turns into an embodiment of curiosity once she says, "I\'m curious." Fukube is a smiling boy with a fantastic memory who calls himself a database. Ibara is a short girl and is strict with others and herself. They begin to investigate a case that occurred 45 years ago. Hints of the mystery are buried in an old collection of works of the former members of Classics Club. The collection is titled "Hyouka."',
    poster_path: "/dnYx8jtn2JzAMkVYRG9mFZMJoDc.jpg",
    media_type: "tv",
    genre_ids: [16, 18, 9648, 35],
    popularity: 71.533,
    first_air_date: "2012-04-23",
    vote_average: 8.151,
    vote_count: 302,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/jSTglzkXYPMOI6sNdXGqGM02AP2.jpg",
    id: 85349,
    name: "Amphibia",
    original_language: "en",
    original_name: "Amphibia",
    overview:
      "The adventures of 13-year-old, self-centered Anne Boonchuy who is magically transported to the fictitious world of Amphibia, a rural marshland full of frog-people. With the help of an excitable young frog named Sprig, Anne will become a hero and discover the first true friendship of her life.",
    poster_path: "/bFCgv9iWZECWSDxNQYc9soqvwjx.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10759, 10765, 10751],
    popularity: 258.811,
    first_air_date: "2019-06-17",
    vote_average: 8.526,
    vote_count: 235,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2f8OLO6UYp78dIQMs0oi7ja15Bl.jpg",
    id: 65648,
    name: "Maid Sama!",
    original_language: "ja",
    original_name: "会長はメイド様！",
    overview:
      "Misaki Ayuzawa is the first female student council president at a once all-boys school turned co-ed. She rules the school with strict discipline demeanor. But she has a secret—she works at a maid cafe due to her families circumstances. One day the popular A-student and notorious heart breaker Takumi Usui finds out her secret and makes a deal with her to keep it hush from the school in exchange for spending some time with him.",
    poster_path: "/igkn0M1bgMeATz59LShvVxZNdVd.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 18],
    popularity: 37.327,
    first_air_date: "2010-04-02",
    vote_average: 8.532,
    vote_count: 534,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/ytAgbDJJHKjRl5WIESX9W5by8XL.jpg",
    id: 32515,
    name: "E Dance Academy",
    original_language: "en",
    original_name: "Dance Academy",
    overview:
      "At Sydney's National Dance Academy, a few talented youngsters are recruited for the excruciatingly tough course. It follows Tara Webster, a sheepfarmgirl who's ambition is to be the next best ballerina. Jewish long line of doctors' heir Samuel 'Sammy' and minor juvenile offender Christian are the outsiders but gradually fit in, making new kinds of friends. Star ballerina's daughter Kat also introduces them in the circle of last-year brother Ethan, who already aspires a career as choreographer. Also Abigail, a smart young girl who'll walk over dead bodies to reach the stars tries to sabotage everything and everyone.",
    poster_path: "/dauOWEXAN0ZdHdxm1s2AIIt0Vur.jpg",
    media_type: "tv",
    genre_ids: [35, 18, 10751],
    popularity: 56.761,
    first_air_date: "2010-05-31",
    vote_average: 7.2,
    vote_count: 41,
    origin_country: ["AU"],
  },
  {
    adult: false,
    backdrop_path: "/n6vVs6z8obNbExdD3QHTr4Utu1Z.jpg",
    id: 76479,
    name: "The Boys",
    original_language: "en",
    original_name: "The Boys",
    overview:
      "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
    poster_path: "/7Ns6tO3aYjppI5bFhyYZurOYGBT.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759],
    popularity: 246.198,
    first_air_date: "2019-07-25",
    vote_average: 8.471,
    vote_count: 9204,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/pxeqQX4qFQ0cVxPt5SWZENV5BH3.jpg",
    id: 456,
    name: "The Simpsons",
    original_language: "en",
    original_name: "The Simpsons",
    overview:
      "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
    poster_path: "/vHqeLzYl3dEAutojCO26g0LIkom.jpg",
    media_type: "tv",
    genre_ids: [10751, 16, 35],
    popularity: 893.551,
    first_air_date: "1989-12-17",
    vote_average: 8,
    vote_count: 9444,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/20eIP9o5ebArmu2HxJutaBjhLf4.jpg",
    id: 87108,
    name: "Chernobyl",
    original_language: "en",
    original_name: "Chernobyl",
    overview:
      "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
    poster_path: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 102.674,
    first_air_date: "2019-05-06",
    vote_average: 8.659,
    vote_count: 5745,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/5s0VnyIk2nArAhVnIGVYQiElmea.jpg",
    id: 62286,
    name: "Fear the Walking Dead",
    original_language: "en",
    original_name: "Fear the Walking Dead",
    overview:
      'What did the world look like as it was transforming into the horrifying apocalypse depicted in "The Walking Dead"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.',
    poster_path: "/l7N9aS6VyYvjelKoCB2eZge0Qky.jpg",
    media_type: "tv",
    genre_ids: [10759, 18],
    popularity: 427.843,
    first_air_date: "2015-08-23",
    vote_average: 7.682,
    vote_count: 4721,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 329.463,
    first_air_date: "2016-07-15",
    vote_average: 8.615,
    vote_count: 16741,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/yGNnjoIGOdQy3douq60tULY8teK.jpg",
    id: 63247,
    name: "Westworld",
    original_language: "en",
    original_name: "Westworld",
    overview:
      "A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.",
    poster_path: "/8MfgyFHf7XEboZJPZXCIDqqiz6e.jpg",
    media_type: "tv",
    genre_ids: [10765, 37],
    popularity: 227.921,
    first_air_date: "2016-10-02",
    vote_average: 8.062,
    vote_count: 5171,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/4wwWDjLfJVMt2hh8DIa2rzEx5VS.jpg",
    id: 62425,
    name: "Dark Matter",
    original_language: "en",
    original_name: "Dark Matter",
    overview:
      "The six-person crew of a derelict spaceship awakens from stasis in the farthest reaches of space. Their memories wiped clean, they have no recollection of who they are or how they got on board. The only clue to their identities is a cargo bay full of weaponry and a destination: a remote mining colony that is about to become a war zone. With no idea whose side they are on, they face a deadly decision. Will these amnesiacs turn their backs on history, or will their pasts catch up with them?",
    poster_path: "/oWYOFBvIMkW64n51uD4mdje6k2u.jpg",
    media_type: "tv",
    genre_ids: [10765, 18],
    popularity: 70.578,
    first_air_date: "2015-06-12",
    vote_average: 6.681,
    vote_count: 725,
    origin_country: ["CA"],
  },
];
